---
title: Créer une animation
hero_image: images/banner.png
description: Comment créer une animation sur ton micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2023-09-18"
steps:
  - title: Introduction
