title: Creating an animation
hero_image: images/banner.png
description: How to create an animation on your micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2023-09-18"
steps:
  - 
    title: Introduction
